{"cells":[{"cell_type":"markdown","metadata":{"_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","trusted":true},"source":["**Sentiment Analysis of IMDB Movie Reviews**"]},{"cell_type":"markdown","metadata":{},"source":["**Problem Statement:**\n","\n","In this, we have to predict the number of positive and negative reviews based on sentiments by using different classification models."]},{"cell_type":"markdown","metadata":{"_uuid":"1424638f5259100af9f9a5c1b05bd23cf5b71e51"},"source":["**Import necessary libraries**"]},{"cell_type":"code","execution_count":12,"metadata":{"_cell_guid":"79c7e3d0-c299-4dcb-8224-4455121ee9b0","_uuid":"d629ff2d2480ee46fbb7e2d37f6b5fab8052498a","trusted":true},"outputs":[],"source":["#Load the libraries\n","import numpy as np\n","import pandas as pd\n","import seaborn as sns\n","import matplotlib.pyplot as plt\n","import nltk\n"]},{"cell_type":"code","execution_count":13,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\4138875543.py\", line 6, in <module>\n","    from wordcloud import WordCloud,STOPWORDS\n","ModuleNotFoundError: No module named 'wordcloud'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["from sklearn.feature_extraction.text import CountVectorizer\n","from sklearn.feature_extraction.text import TfidfVectorizer\n","from sklearn.preprocessing import LabelBinarizer\n","from nltk.corpus import stopwords\n","from nltk.stem.porter import PorterStemmer\n","from wordcloud import WordCloud,STOPWORDS\n","from nltk.stem import WordNetLemmatizer\n","from nltk.tokenize import word_tokenize,sent_tokenize\n","from bs4 import BeautifulSoup"]},{"cell_type":"code","execution_count":14,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\4200371057.py\", line 1, in <module>\n","    import spacy\n","ModuleNotFoundError: No module named 'spacy'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["import spacy\n","import re,string,unicodedata\n","from nltk.tokenize.toktok import ToktokTokenizer\n","from nltk.stem import LancasterStemmer,WordNetLemmatizer\n","from sklearn.linear_model import LogisticRegression,SGDClassifier\n","from sklearn.naive_bayes import MultinomialNB\n","from sklearn.svm import SVC\n","from textblob import TextBlob\n","from textblob import Word\n","from sklearn.metrics import classification_report,confusion_matrix,accuracy_score\n"]},{"cell_type":"code","execution_count":15,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\4045611321.py\", line 2, in <module>\n","    print(os.listdir(\"../input\"))\n","          ^^^^^^^^^^^^^^^^^^^^^^\n","FileNotFoundError: [WinError 3] The system cannot find the path specified: '../input'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["import os\n","print(os.listdir(\"../input\"))\n","import warnings\n","warnings.filterwarnings('ignore')\n"]},{"cell_type":"markdown","metadata":{"_uuid":"be1b642cce343f7a8f68f8c91f7c50372cdf4381"},"source":["**Import the training dataset**"]},{"cell_type":"code","execution_count":16,"metadata":{"_uuid":"4c593c17588723c0b0b0f19851cb70a8447ced76","scrolled":true,"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\3247392801.py\", line 2, in <module>\n","    imdb_data=pd.read_csv('../input/IMDB Dataset.csv')\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 912, in read_csv\n","    return _read(filepath_or_buffer, kwds)\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 577, in _read\n","    parser = TextFileReader(filepath_or_buffer, **kwds)\n","             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1407, in __init__\n","    self._engine = self._make_engine(f, self.engine)\n","                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1661, in _make_engine\n","    self.handles = get_handle(\n","                   ^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pandas\\io\\common.py\", line 859, in get_handle\n","    handle = open(\n","             ^^^^^\n","FileNotFoundError: [Errno 2] No such file or directory: '../input/IMDB Dataset.csv'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#importing the training data\n","imdb_data=pd.read_csv('../input/IMDB Dataset.csv')\n","print(imdb_data.shape)\n","imdb_data.head(10)"]},{"cell_type":"markdown","metadata":{"_uuid":"1ad3773974351ed9bdf389b2847d7475b36c2295"},"source":["**Exploratery data analysis**"]},{"cell_type":"code","execution_count":17,"metadata":{"_uuid":"7f11c83b1320c8982b36889145f7f770563674a8","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\628525732.py\", line 2, in <module>\n","    imdb_data.describe()\n","    ^^^^^^^^^\n","NameError: name 'imdb_data' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Summary of the dataset\n","imdb_data.describe()"]},{"cell_type":"markdown","metadata":{"_uuid":"453c3fd238f62ab8f649eb01771817e25bc0c77d"},"source":["**Sentiment count**"]},{"cell_type":"code","execution_count":18,"metadata":{"_uuid":"cb6bb97b0f851947dcf341a1de5708a1f2bc64c1","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\1961701049.py\", line 2, in <module>\n","    imdb_data['sentiment'].value_counts()\n","    ^^^^^^^^^\n","NameError: name 'imdb_data' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#sentiment count\n","imdb_data['sentiment'].value_counts()"]},{"cell_type":"markdown","metadata":{},"source":["We can see that the dataset is balanced."]},{"cell_type":"markdown","metadata":{"_uuid":"f61964573faababe1f7897b77d32815a24954d2f"},"source":["**Spliting the training dataset**"]},{"cell_type":"code","execution_count":19,"metadata":{"_uuid":"d3aaabff555e07feb11c72cc3a6e457615975ffe","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\2480793252.py\", line 3, in <module>\n","    train_reviews=imdb_data.review[:40000]\n","                  ^^^^^^^^^\n","NameError: name 'imdb_data' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#split the dataset  \n","#train dataset\n","train_reviews=imdb_data.review[:40000]\n","train_sentiments=imdb_data.sentiment[:40000]\n","#test dataset\n","test_reviews=imdb_data.review[40000:]\n","test_sentiments=imdb_data.sentiment[40000:]\n","print(train_reviews.shape,train_sentiments.shape)\n","print(test_reviews.shape,test_sentiments.shape)"]},{"cell_type":"markdown","metadata":{"_uuid":"90da29c3b79f46f41d7391a2a116065b616d0fac"},"source":["**Text normalization**"]},{"cell_type":"code","execution_count":20,"metadata":{"_uuid":"f000c43d91f68f6668539f089c6a54c5ce3bd819","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\1515494159.py\", line 2, in <module>\n","    tokenizer=ToktokTokenizer()\n","              ^^^^^^^^^^^^^^^\n","NameError: name 'ToktokTokenizer' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Tokenization of text\n","tokenizer=ToktokTokenizer()\n","#Setting English stopwords\n","stopword_list=nltk.corpus.stopwords.words('english')"]},{"cell_type":"markdown","metadata":{"_uuid":"328b6e5977da3e055ad4b2e11a31e5e12ccf3b16"},"source":["**Removing html strips and noise text**"]},{"cell_type":"code","execution_count":21,"metadata":{"_uuid":"6f6fcafbdadcdcb0c164e37d71fb9d1623f74d0a","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\841911545.py\", line 16, in <module>\n","    imdb_data['review']=imdb_data['review'].apply(denoise_text)\n","                        ^^^^^^^^^\n","NameError: name 'imdb_data' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Removing the html strips\n","def strip_html(text):\n","    soup = BeautifulSoup(text, \"html.parser\")\n","    return soup.get_text()\n","\n","#Removing the square brackets\n","def remove_between_square_brackets(text):\n","    return re.sub('\\[[^]]*\\]', '', text)\n","\n","#Removing the noisy text\n","def denoise_text(text):\n","    text = strip_html(text)\n","    text = remove_between_square_brackets(text)\n","    return text\n","#Apply function on review column\n","imdb_data['review']=imdb_data['review'].apply(denoise_text)"]},{"cell_type":"markdown","metadata":{"_uuid":"88117b74761d1047924d6d70f76642faa0e706ac"},"source":["**Removing special characters**"]},{"cell_type":"code","execution_count":22,"metadata":{"_uuid":"219da72b025121fd98081df50ae0fcaace10cc9d","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\3405533479.py\", line 7, in <module>\n","    imdb_data['review']=imdb_data['review'].apply(remove_special_characters)\n","                        ^^^^^^^^^\n","NameError: name 'imdb_data' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Define function for removing special characters\n","def remove_special_characters(text, remove_digits=True):\n","    pattern=r'[^a-zA-z0-9\\s]'\n","    text=re.sub(pattern,'',text)\n","    return text\n","#Apply function on review column\n","imdb_data['review']=imdb_data['review'].apply(remove_special_characters)"]},{"cell_type":"markdown","metadata":{"_uuid":"3b66eeabd5b7b8c251f8b8ddf331140a64bcd514"},"source":["**Text stemming\n","**"]},{"cell_type":"code","execution_count":23,"metadata":{"_uuid":"2295f2946e0ab74c220ad538d0e7adc04d23f697","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\2560446488.py\", line 7, in <module>\n","    imdb_data['review']=imdb_data['review'].apply(simple_stemmer)\n","                        ^^^^^^^^^\n","NameError: name 'imdb_data' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Stemming the text\n","def simple_stemmer(text):\n","    ps=nltk.porter.PorterStemmer()\n","    text= ' '.join([ps.stem(word) for word in text.split()])\n","    return text\n","#Apply function on review column\n","imdb_data['review']=imdb_data['review'].apply(simple_stemmer)"]},{"cell_type":"markdown","metadata":{"_uuid":"e83107e4a281d84d7ae42b4e2c8d81b7ece438e4"},"source":["**Removing stopwords**"]},{"cell_type":"code","execution_count":24,"metadata":{"_uuid":"5dbff82b4d2d188d8777b273a75d8ac714d38885","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["{'do', 'wasn', \"weren't\", 'this', 'about', 'while', 'had', 'm', 'here', 'any', 'didn', 'they', 'most', 'just', \"it's\", 'mightn', 'll', 'why', 'but', 's', 'below', 'these', 'then', 'doing', 'don', 'such', 've', 'after', 'can', \"needn't\", \"you're\", \"you've\", 'own', 'from', 'more', 'other', 'which', 'aren', 'shan', 'an', 'hers', 'should', 'as', 'd', 'out', \"wasn't\", \"don't\", 'your', \"she's\", 'needn', 'with', 'our', \"shouldn't\", 'shouldn', 'a', 'did', 'by', 'hadn', 'between', 'them', 'myself', 'if', 'its', 'than', 'been', 'into', 'he', 'now', \"isn't\", 'on', \"won't\", \"hasn't\", 'ourselves', 'that', 'their', 'o', 'being', 'yourself', 'have', 'who', \"aren't\", 'yourselves', \"that'll\", 'further', 'down', \"shan't\", 'was', 'the', \"you'll\", 'theirs', 'off', \"didn't\", 'i', 'himself', 'during', 'me', 'until', 'she', 'to', \"couldn't\", 't', 'am', \"you'd\", 'isn', 'so', 'against', 'haven', 'of', 'for', 'very', 'my', 'couldn', 'all', 'him', \"haven't\", 'wouldn', 'will', 'weren', 'above', 'again', 'are', 'does', 'we', 'once', \"mustn't\", 'her', 'through', 're', 'themselves', 'hasn', 'because', 'each', 'both', \"hadn't\", 'how', 'is', 'yours', 'ain', 'what', 'up', \"mightn't\", 'when', 'or', 'mustn', 'at', 'over', 'in', 'under', 'there', 'only', \"should've\", 'his', 'herself', 'it', 'few', 'where', 'has', 'won', 'before', 'not', 'you', 'no', 'nor', 'whom', 'too', 'itself', 'having', 'y', 'same', 'ma', 'ours', \"wouldn't\", 'some', 'and', \"doesn't\", 'those', 'be', 'were', 'doesn'}\n","Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\3967792148.py\", line 16, in <module>\n","    imdb_data['review']=imdb_data['review'].apply(remove_stopwords)\n","                        ^^^^^^^^^\n","NameError: name 'imdb_data' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#set stopwords to english\n","stop=set(stopwords.words('english'))\n","print(stop)\n","\n","#removing the stopwords\n","def remove_stopwords(text, is_lower_case=False):\n","    tokens = tokenizer.tokenize(text)\n","    tokens = [token.strip() for token in tokens]\n","    if is_lower_case:\n","        filtered_tokens = [token for token in tokens if token not in stopword_list]\n","    else:\n","        filtered_tokens = [token for token in tokens if token.lower() not in stopword_list]\n","    filtered_text = ' '.join(filtered_tokens)    \n","    return filtered_text\n","#Apply function on review column\n","imdb_data['review']=imdb_data['review'].apply(remove_stopwords)"]},{"cell_type":"markdown","metadata":{"_uuid":"b35e7499291173119ed42287deac6f0cd96516e1"},"source":["**Normalized train reviews**"]},{"cell_type":"code","execution_count":25,"metadata":{"_kg_hide-output":true,"_uuid":"b20c242bd091929ca896ea2c6e936ca00efe6ecf","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\498785779.py\", line 2, in <module>\n","    norm_train_reviews=imdb_data.review[:40000]\n","                       ^^^^^^^^^\n","NameError: name 'imdb_data' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#normalized train reviews\n","norm_train_reviews=imdb_data.review[:40000]\n","norm_train_reviews[0]\n","#convert dataframe to string\n","#norm_train_string=norm_train_reviews.to_string()\n","#Spelling correction using Textblob\n","#norm_train_spelling=TextBlob(norm_train_string)\n","#norm_train_spelling.correct()\n","#Tokenization using Textblob\n","#norm_train_words=norm_train_spelling.words\n","#norm_train_words"]},{"cell_type":"markdown","metadata":{"_uuid":"d69462bb209a66cff86376dc8481d0c0140d894d"},"source":["**Normalized test reviews**"]},{"cell_type":"code","execution_count":26,"metadata":{"_kg_hide-output":true,"_uuid":"c5d0d38bd9976150367e9d75f3b933774c96a1ab","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\1514591528.py\", line 2, in <module>\n","    norm_test_reviews=imdb_data.review[40000:]\n","                      ^^^^^^^^^\n","NameError: name 'imdb_data' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Normalized test reviews\n","norm_test_reviews=imdb_data.review[40000:]\n","norm_test_reviews[45005]\n","##convert dataframe to string\n","#norm_test_string=norm_test_reviews.to_string()\n","#spelling correction using Textblob\n","#norm_test_spelling=TextBlob(norm_test_string)\n","#print(norm_test_spelling.correct())\n","#Tokenization using Textblob\n","#norm_test_words=norm_test_spelling.words\n","#norm_test_words"]},{"cell_type":"markdown","metadata":{"_uuid":"1c2a872ffcb6b8076fdbbba641af12081b6022ef"},"source":["**Bags of words model **\n","\n","It is used to convert text documents to numerical vectors or bag of words."]},{"cell_type":"code","execution_count":27,"metadata":{"_uuid":"35cf9dcefb40b2dc520c5b0d559695324c46cc04","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\171210400.py\", line 4, in <module>\n","    cv_train_reviews=cv.fit_transform(norm_train_reviews)\n","                                      ^^^^^^^^^^^^^^^^^^\n","NameError: name 'norm_train_reviews' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Count vectorizer for bag of words\n","cv=CountVectorizer(min_df=0,max_df=1,binary=False,ngram_range=(1,3))\n","#transformed train reviews\n","cv_train_reviews=cv.fit_transform(norm_train_reviews)\n","#transformed test reviews\n","cv_test_reviews=cv.transform(norm_test_reviews)\n","\n","print('BOW_cv_train:',cv_train_reviews.shape)\n","print('BOW_cv_test:',cv_test_reviews.shape)\n","#vocab=cv.get_feature_names()-toget feature names"]},{"cell_type":"markdown","metadata":{"_uuid":"52371868f05ff9cf157280c5acf0f5bc71ee176d"},"source":["**Term Frequency-Inverse Document Frequency model (TFIDF)**\n","\n","It is used to convert text documents to  matrix of  tfidf features."]},{"cell_type":"code","execution_count":28,"metadata":{"_uuid":"afe6de957339921e05a6faeaf731f2272fd31946","scrolled":false,"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\1026808502.py\", line 4, in <module>\n","    tv_train_reviews=tv.fit_transform(norm_train_reviews)\n","                                      ^^^^^^^^^^^^^^^^^^\n","NameError: name 'norm_train_reviews' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Tfidf vectorizer\n","tv=TfidfVectorizer(min_df=0,max_df=1,use_idf=True,ngram_range=(1,3))\n","#transformed train reviews\n","tv_train_reviews=tv.fit_transform(norm_train_reviews)\n","#transformed test reviews\n","tv_test_reviews=tv.transform(norm_test_reviews)\n","print('Tfidf_train:',tv_train_reviews.shape)\n","print('Tfidf_test:',tv_test_reviews.shape)"]},{"cell_type":"markdown","metadata":{"_uuid":"803e92b25faa738b10928a91de72d177d8dddf85"},"source":["**Labeling the sentiment text**"]},{"cell_type":"code","execution_count":29,"metadata":{"_uuid":"60f5d496ce4109d1cdbf08f4284d4d26efd93922","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\964274203.py\", line 4, in <module>\n","    sentiment_data=lb.fit_transform(imdb_data['sentiment'])\n","                                    ^^^^^^^^^\n","NameError: name 'imdb_data' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#labeling the sentient data\n","lb=LabelBinarizer()\n","#transformed sentiment data\n","sentiment_data=lb.fit_transform(imdb_data['sentiment'])\n","print(sentiment_data.shape)"]},{"cell_type":"markdown","metadata":{"_uuid":"21a80c94fb42e14391c627710c5d796c40aa7dde"},"source":["**Split the sentiment tdata**"]},{"cell_type":"code","execution_count":30,"metadata":{"_kg_hide-output":true,"_uuid":"ca1e4cc917265ac98a72c37cffe57f27e9897408","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\3806812550.py\", line 2, in <module>\n","    train_sentiments=sentiment_data[:40000]\n","                     ^^^^^^^^^^^^^^\n","NameError: name 'sentiment_data' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Spliting the sentiment data\n","train_sentiments=sentiment_data[:40000]\n","test_sentiments=sentiment_data[40000:]\n","print(train_sentiments)\n","print(test_sentiments)"]},{"cell_type":"markdown","metadata":{},"source":["**Modelling the dataset**"]},{"cell_type":"markdown","metadata":{"_uuid":"d5e45fdc9d062a5b9b9dd665ffe732776e196953"},"source":["Let us build logistic regression model for both bag of words and tfidf features"]},{"cell_type":"code","execution_count":31,"metadata":{"_uuid":"142d007421900550079a12ae8655bcae678ebaad","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\2045866752.py\", line 2, in <module>\n","    lr=LogisticRegression(penalty='l2',max_iter=500,C=1,random_state=42)\n","       ^^^^^^^^^^^^^^^^^^\n","NameError: name 'LogisticRegression' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#training the model\n","lr=LogisticRegression(penalty='l2',max_iter=500,C=1,random_state=42)\n","#Fitting the model for Bag of words\n","lr_bow=lr.fit(cv_train_reviews,train_sentiments)\n","print(lr_bow)\n","#Fitting the model for tfidf features\n","lr_tfidf=lr.fit(tv_train_reviews,train_sentiments)\n","print(lr_tfidf)"]},{"cell_type":"markdown","metadata":{"_uuid":"07eb6d52eb32469e3be82e90af636d598a7b7c27"},"source":["**Logistic regression model performane on test dataset**"]},{"cell_type":"code","execution_count":32,"metadata":{"_uuid":"52ad86935b76117f97b79e6672a3ba12352b9461","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\1407752404.py\", line 2, in <module>\n","    lr_bow_predict=lr.predict(cv_test_reviews)\n","                   ^^\n","NameError: name 'lr' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Predicting the model for bag of words\n","lr_bow_predict=lr.predict(cv_test_reviews)\n","print(lr_bow_predict)\n","##Predicting the model for tfidf features\n","lr_tfidf_predict=lr.predict(tv_test_reviews)\n","print(lr_tfidf_predict)"]},{"cell_type":"markdown","metadata":{},"source":["**Accuracy of the model**"]},{"cell_type":"code","execution_count":33,"metadata":{"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\2001475528.py\", line 2, in <module>\n","    lr_bow_score=accuracy_score(test_sentiments,lr_bow_predict)\n","                 ^^^^^^^^^^^^^^\n","NameError: name 'accuracy_score' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Accuracy score for bag of words\n","lr_bow_score=accuracy_score(test_sentiments,lr_bow_predict)\n","print(\"lr_bow_score :\",lr_bow_score)\n","#Accuracy score for tfidf features\n","lr_tfidf_score=accuracy_score(test_sentiments,lr_tfidf_predict)\n","print(\"lr_tfidf_score :\",lr_tfidf_score)"]},{"cell_type":"markdown","metadata":{"_uuid":"ac2ec8353acb5e0f548e1e4a590fbe6f34f4a686"},"source":["**Print the classification report**"]},{"cell_type":"code","execution_count":34,"metadata":{"_uuid":"f89c7e7a6136d08790ffbf6bc4d0d05455f8555a","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\628648140.py\", line 2, in <module>\n","    lr_bow_report=classification_report(test_sentiments,lr_bow_predict,target_names=['Positive','Negative'])\n","                  ^^^^^^^^^^^^^^^^^^^^^\n","NameError: name 'classification_report' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Classification report for bag of words \n","lr_bow_report=classification_report(test_sentiments,lr_bow_predict,target_names=['Positive','Negative'])\n","print(lr_bow_report)\n","\n","#Classification report for tfidf features\n","lr_tfidf_report=classification_report(test_sentiments,lr_tfidf_predict,target_names=['Positive','Negative'])\n","print(lr_tfidf_report)"]},{"cell_type":"markdown","metadata":{"_uuid":"0d2e5ddcd69ff0fb52f05f17fc74a86e1b5e5b61"},"source":["**Confusion matrix**"]},{"cell_type":"code","execution_count":35,"metadata":{"_uuid":"a36c058e834938559b7202f2142e61423a613b7a","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\1011994345.py\", line 2, in <module>\n","    cm_bow=confusion_matrix(test_sentiments,lr_bow_predict,labels=[1,0])\n","           ^^^^^^^^^^^^^^^^\n","NameError: name 'confusion_matrix' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#confusion matrix for bag of words\n","cm_bow=confusion_matrix(test_sentiments,lr_bow_predict,labels=[1,0])\n","print(cm_bow)\n","#confusion matrix for tfidf features\n","cm_tfidf=confusion_matrix(test_sentiments,lr_tfidf_predict,labels=[1,0])\n","print(cm_tfidf)"]},{"cell_type":"markdown","metadata":{"_uuid":"8fde9753386e3593dc27c4e88e02bdc38462a018"},"source":["**Stochastic gradient descent or Linear support vector machines for bag of words and tfidf features**"]},{"cell_type":"code","execution_count":36,"metadata":{"_uuid":"2211a9e97682195a0372b33e4da7267aad8548db","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\2656121863.py\", line 2, in <module>\n","    svm=SGDClassifier(loss='hinge',max_iter=500,random_state=42)\n","        ^^^^^^^^^^^^^\n","NameError: name 'SGDClassifier' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#training the linear svm\n","svm=SGDClassifier(loss='hinge',max_iter=500,random_state=42)\n","#fitting the svm for bag of words\n","svm_bow=svm.fit(cv_train_reviews,train_sentiments)\n","print(svm_bow)\n","#fitting the svm for tfidf features\n","svm_tfidf=svm.fit(tv_train_reviews,train_sentiments)\n","print(svm_tfidf)"]},{"cell_type":"markdown","metadata":{"_uuid":"e9a7a973591c1d3cabaa1a47c57fa029d3752bab"},"source":["**Model performance on test data**"]},{"cell_type":"code","execution_count":37,"metadata":{"_uuid":"1a5ab738e04f0f9082c8d6ade6c2148cc398f8f3","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\1784965022.py\", line 2, in <module>\n","    svm_bow_predict=svm.predict(cv_test_reviews)\n","                    ^^^\n","NameError: name 'svm' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Predicting the model for bag of words\n","svm_bow_predict=svm.predict(cv_test_reviews)\n","print(svm_bow_predict)\n","#Predicting the model for tfidf features\n","svm_tfidf_predict=svm.predict(tv_test_reviews)\n","print(svm_tfidf_predict)"]},{"cell_type":"markdown","metadata":{},"source":["**Accuracy of the model**"]},{"cell_type":"code","execution_count":38,"metadata":{"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\1388722288.py\", line 2, in <module>\n","    svm_bow_score=accuracy_score(test_sentiments,svm_bow_predict)\n","                  ^^^^^^^^^^^^^^\n","NameError: name 'accuracy_score' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Accuracy score for bag of words\n","svm_bow_score=accuracy_score(test_sentiments,svm_bow_predict)\n","print(\"svm_bow_score :\",svm_bow_score)\n","#Accuracy score for tfidf features\n","svm_tfidf_score=accuracy_score(test_sentiments,svm_tfidf_predict)\n","print(\"svm_tfidf_score :\",svm_tfidf_score)"]},{"cell_type":"markdown","metadata":{"_uuid":"b1bd245f50902ad87ca28e48cbce64ec6a16ec5a"},"source":["**Print the classification report**"]},{"cell_type":"code","execution_count":39,"metadata":{"_uuid":"d112bc5b4944330b567e19a7e04544a9a459f238","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\2388935844.py\", line 2, in <module>\n","    svm_bow_report=classification_report(test_sentiments,svm_bow_predict,target_names=['Positive','Negative'])\n","                   ^^^^^^^^^^^^^^^^^^^^^\n","NameError: name 'classification_report' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Classification report for bag of words \n","svm_bow_report=classification_report(test_sentiments,svm_bow_predict,target_names=['Positive','Negative'])\n","print(svm_bow_report)\n","#Classification report for tfidf features\n","svm_tfidf_report=classification_report(test_sentiments,svm_tfidf_predict,target_names=['Positive','Negative'])\n","print(svm_tfidf_report)"]},{"cell_type":"markdown","metadata":{"_uuid":"705fd8ae8bb5e6925852fffc906b6ffd769dbac0"},"source":["**Plot the confusion matrix**"]},{"cell_type":"code","execution_count":40,"metadata":{"_uuid":"49cde912705acbaef90d7a269cd27ea8a2815f03","trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\255180976.py\", line 2, in <module>\n","    cm_bow=confusion_matrix(test_sentiments,svm_bow_predict,labels=[1,0])\n","           ^^^^^^^^^^^^^^^^\n","NameError: name 'confusion_matrix' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#confusion matrix for bag of words\n","cm_bow=confusion_matrix(test_sentiments,svm_bow_predict,labels=[1,0])\n","print(cm_bow)\n","#confusion matrix for tfidf features\n","cm_tfidf=confusion_matrix(test_sentiments,svm_tfidf_predict,labels=[1,0])\n","print(cm_tfidf)"]},{"cell_type":"markdown","metadata":{},"source":["**Multinomial Naive Bayes for bag of words and tfidf features**"]},{"cell_type":"code","execution_count":41,"metadata":{"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\3628149404.py\", line 2, in <module>\n","    mnb=MultinomialNB()\n","        ^^^^^^^^^^^^^\n","NameError: name 'MultinomialNB' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#training the model\n","mnb=MultinomialNB()\n","#fitting the svm for bag of words\n","mnb_bow=mnb.fit(cv_train_reviews,train_sentiments)\n","print(mnb_bow)\n","#fitting the svm for tfidf features\n","mnb_tfidf=mnb.fit(tv_train_reviews,train_sentiments)\n","print(mnb_tfidf)"]},{"cell_type":"markdown","metadata":{},"source":["**Model performance on test data**"]},{"cell_type":"code","execution_count":42,"metadata":{"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\3175512909.py\", line 2, in <module>\n","    mnb_bow_predict=mnb.predict(cv_test_reviews)\n","                    ^^^\n","NameError: name 'mnb' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Predicting the model for bag of words\n","mnb_bow_predict=mnb.predict(cv_test_reviews)\n","print(mnb_bow_predict)\n","#Predicting the model for tfidf features\n","mnb_tfidf_predict=mnb.predict(tv_test_reviews)\n","print(mnb_tfidf_predict)"]},{"cell_type":"markdown","metadata":{},"source":["**Accuracy of the model**"]},{"cell_type":"code","execution_count":43,"metadata":{"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\2526707824.py\", line 2, in <module>\n","    mnb_bow_score=accuracy_score(test_sentiments,mnb_bow_predict)\n","                  ^^^^^^^^^^^^^^\n","NameError: name 'accuracy_score' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Accuracy score for bag of words\n","mnb_bow_score=accuracy_score(test_sentiments,mnb_bow_predict)\n","print(\"mnb_bow_score :\",mnb_bow_score)\n","#Accuracy score for tfidf features\n","mnb_tfidf_score=accuracy_score(test_sentiments,mnb_tfidf_predict)\n","print(\"mnb_tfidf_score :\",mnb_tfidf_score)"]},{"cell_type":"markdown","metadata":{},"source":["**Print the classification report**"]},{"cell_type":"code","execution_count":44,"metadata":{"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\2345273443.py\", line 2, in <module>\n","    mnb_bow_report=classification_report(test_sentiments,mnb_bow_predict,target_names=['Positive','Negative'])\n","                   ^^^^^^^^^^^^^^^^^^^^^\n","NameError: name 'classification_report' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#Classification report for bag of words \n","mnb_bow_report=classification_report(test_sentiments,mnb_bow_predict,target_names=['Positive','Negative'])\n","print(mnb_bow_report)\n","#Classification report for tfidf features\n","mnb_tfidf_report=classification_report(test_sentiments,mnb_tfidf_predict,target_names=['Positive','Negative'])\n","print(mnb_tfidf_report)"]},{"cell_type":"markdown","metadata":{},"source":["**Plot the confusion matrix**"]},{"cell_type":"code","execution_count":45,"metadata":{"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\3260946800.py\", line 2, in <module>\n","    cm_bow=confusion_matrix(test_sentiments,mnb_bow_predict,labels=[1,0])\n","           ^^^^^^^^^^^^^^^^\n","NameError: name 'confusion_matrix' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]}],"source":["#confusion matrix for bag of words\n","cm_bow=confusion_matrix(test_sentiments,mnb_bow_predict,labels=[1,0])\n","print(cm_bow)\n","#confusion matrix for tfidf features\n","cm_tfidf=confusion_matrix(test_sentiments,mnb_tfidf_predict,labels=[1,0])\n","print(cm_tfidf)"]},{"cell_type":"markdown","metadata":{},"source":["**Let us see positive and negative words by using WordCloud.**"]},{"cell_type":"markdown","metadata":{},"source":["**Word cloud for positive review words**"]},{"cell_type":"code","execution_count":46,"metadata":{"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\3777389212.py\", line 3, in <module>\n","    positive_text=norm_train_reviews[1]\n","                  ^^^^^^^^^^^^^^^^^^\n","NameError: name 'norm_train_reviews' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]},{"data":{"text/plain":["<Figure size 1000x1000 with 0 Axes>"]},"metadata":{},"output_type":"display_data"}],"source":["#word cloud for positive review words\n","plt.figure(figsize=(10,10))\n","positive_text=norm_train_reviews[1]\n","WC=WordCloud(width=1000,height=500,max_words=500,min_font_size=5)\n","positive_words=WC.generate(positive_text)\n","plt.imshow(positive_words,interpolation='bilinear')\n","plt.show"]},{"cell_type":"markdown","metadata":{},"source":["**Word cloud for negative review words**"]},{"cell_type":"code","execution_count":47,"metadata":{"trusted":true},"outputs":[{"name":"stdout","output_type":"stream","text":["Unexpected exception formatting exception. Falling back to standard exception\n"]},{"name":"stderr","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3508, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\Dell\\AppData\\Local\\Temp\\ipykernel_23668\\2887260513.py\", line 3, in <module>\n","    negative_text=norm_train_reviews[8]\n","                  ^^^^^^^^^^^^^^^^^^\n","NameError: name 'norm_train_reviews' is not defined\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2105, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1396, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1140, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1030, in format_exception_as_a_whole\n","    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in get_records\n","    style = stack_data.style_with_executing_node(style, self._tb_highlight)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n","    class NewStyle(style):\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 91, in __new__\n","    ndef[4] = colorformat(styledef[3:])\n","              ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"c:\\Users\\Dell\\anaconda3\\Lib\\site-packages\\pygments\\style.py\", line 58, in colorformat\n","    assert False, \"wrong color format %r\" % text\n","AssertionError: wrong color format 'ansiyellow'\n"]},{"data":{"text/plain":["<Figure size 1000x1000 with 0 Axes>"]},"metadata":{},"output_type":"display_data"}],"source":["#Word cloud for negative review words\n","plt.figure(figsize=(10,10))\n","negative_text=norm_train_reviews[8]\n","WC=WordCloud(width=1000,height=500,max_words=500,min_font_size=5)\n","negative_words=WC.generate(negative_text)\n","plt.imshow(negative_words,interpolation='bilinear')\n","plt.show"]},{"cell_type":"markdown","metadata":{},"source":["**Conclusion:**\n","* We can observed that both logistic regression and multinomial naive bayes model performing well compared to linear support vector  machines.\n","* Still we can improve the accuracy of the models by preprocessing data and by using lexicon models like Textblob."]}],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.4"}},"nbformat":4,"nbformat_minor":4}
